package scapi::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'scapi::Schema',

    connect_info => {
        dsn => 'dbi:mysql:database=scapi_db;host=scapi-db.cluster-c9syuayperbe.us-east-1.rds.amazonaws.com',
        user => 'scapi_user',
        password => 'XXXXXX',
        AutoCommit => q{1},
    }
);

=head1 NAME

scapi::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<scapi>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<scapi::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

EC2 Default User

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
